export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface CourseExam {
  courseId: string;
  title: string;
  description: string;
  passingScore: number;
  questions: QuizQuestion[];
}

// Helper to generate consistent IDs
function q(id: string, question: string, options: string[], correct: number, explanation: string): QuizQuestion {
  return { id, question, options, correctIndex: correct, explanation };
}

const iso9001Questions: QuizQuestion[] = [
  q('q1', 'What is the primary purpose of ISO 9001:2015?', ['To increase company profits', 'To demonstrate ability to consistently provide products and services that meet customer and regulatory requirements', 'To reduce employee headcount', 'To eliminate all documentation'], 1, 'ISO 9001:2015 specifies requirements for a QMS when an organization needs to demonstrate its ability to consistently provide products and services that meet customer and applicable statutory and regulatory requirements.'),
  q('q2', 'How many Quality Management Principles are defined in ISO 9000:2015?', ['5', '7', '8', '10'], 1, 'The 7 QMPs are: Customer Focus, Leadership, Engagement of People, Process Approach, Improvement, Evidence-based Decisions, and Relationship Management.'),
  q('q3', 'What does "Context of the Organization" (Clause 4) require?', ['Only internal financial reports', 'Understanding internal and external issues relevant to the QMS purpose and strategic direction', 'Employee vacation schedules', 'Marketing campaign budgets'], 1, 'Clause 4 requires determining external and internal issues relevant to the organization\'s purpose and strategic direction that affect its ability to achieve the intended results.'),
  q('q4', 'Who is responsible for the effectiveness of the QMS?', ['Only the Quality Manager', 'Top Management', 'External auditors only', 'Frontline employees only'], 1, 'Clause 5 (Leadership) states that Top Management must demonstrate leadership and commitment with respect to the QMS, including taking accountability for its effectiveness.'),
  q('q5', 'What is the PDCA cycle used for in ISO 9001?', ['Only for manufacturing processes', 'A methodology for achieving continuous improvement throughout the QMS', 'Employee scheduling', 'Budget planning only'], 1, 'PDCA is Plan-Do-Check-Act: an iterative methodology used for achieving continuous improvement.'),
  q('q6', 'What does "Risk-Based Thinking" require?', ['Ignoring all risks', 'Determining risks and opportunities to give assurance the QMS achieves its intended results', 'Only focusing on financial risks', 'Eliminating all risk documentation'], 1, 'Risk-based thinking requires the organization to determine the risks and opportunities that need to be addressed.'),
  q('q7', 'What is required for "Documented Information" in ISO 9001:2015?', ['A 500-page quality manual', 'Information required by the standard and determined by the organization as necessary', 'Only electronic documents', 'Only paper documents'], 1, 'ISO 9001:2015 uses "documented information" as a flexible term including information required by the standard and determined necessary.'),
  q('q8', 'What is the purpose of Internal Audit (Clause 9.2)?', ['To punish employees', 'To provide information on whether the QMS conforms to requirements', 'To replace management review', 'To eliminate external audits'], 1, 'Clause 9.2 requires internal audits to provide information on whether the QMS conforms to requirements and is effectively implemented.'),
  q('q9', 'What is "Management Review" (Clause 9.3)?', ['An annual financial report', 'A periodic review by top management of the QMS', 'Employee performance reviews', 'Customer satisfaction surveys only'], 1, 'Management Review requires top management to review the QMS at planned intervals for continuing suitability, adequacy, and effectiveness.'),
  q('q10', 'What does "Continual Improvement" (Clause 10) require?', ['One-time changes only', 'Continually improving the suitability, adequacy, and effectiveness of the QMS', 'Annual restructuring', 'Replacing the QMS every 3 years'], 1, 'Clause 10 requires the organization to continually improve the suitability, adequacy, and effectiveness of the QMS.'),
  q('q11', 'What is the Annex SL High Level Structure (HLS)?', ['A type of audit checklist', 'A common framework for all new ISO management system standards', 'A software application', 'A training manual'], 1, 'Annex SL provides a common top-level structure, identical core text, and common terms/definitions for all new ISO management system standards.'),
  q('q12', 'What is a "Quality Policy"?', ['A marketing slogan', 'A formal statement from top management describing the organization\'s quality intentions', 'A production schedule', 'Customer complaint form'], 1, 'The quality policy is a formal statement from management that describes the organization\'s quality intentions and direction.'),
  q('q13', 'What are "Interested Parties" in ISO 9001?', ['Only shareholders', 'Persons or organizations who can affect or be affected by the organization\'s decisions', 'Only customers', 'Only government regulators'], 1, 'Interested parties include persons or organizations who can affect, be affected by, or perceive themselves to be affected by decisions or activities.'),
  q('q14', 'What is the purpose of "Corrective Action"?', ['To fix a problem immediately', 'To eliminate the cause of a nonconformity and prevent recurrence', 'To blame an employee', 'To hide a problem from auditors'], 1, 'Corrective action is action to eliminate the cause of a nonconformity and to prevent recurrence.'),
  q('q15', 'What is a "Nonconformity" in ISO 9001?', ['A type of audit report', 'Non-fulfillment of a requirement', 'A customer complaint only', 'A financial loss'], 1, 'Nonconformity is the non-fulfillment of a requirement.'),
];

const iso14001Questions: QuizQuestion[] = [
  q('q1', 'What is the purpose of ISO 14001:2015?', ['To increase profits', 'To provide a framework for environmental management', 'To reduce employee count', 'To eliminate all waste'], 1, 'ISO 14001:2015 specifies requirements for an environmental management system that an organization can use to enhance its environmental performance.'),
  q('q2', 'What are "Environmental Aspects"?', ['Beautiful landscapes', 'Elements of an organization\'s activities that can interact with the environment', 'Financial reports', 'Employee benefits'], 1, 'Environmental aspects are elements of an organization\'s activities, products, or services that can interact with the environment.'),
  q('q3', 'What is an "Environmental Impact"?', ['A financial loss', 'Any change to the environment, whether adverse or beneficial', 'A type of insurance', 'A marketing strategy'], 1, 'Environmental impact is any change to the environment, whether adverse or beneficial, wholly or partially resulting from an organization\'s activities.'),
  q('q4', 'What does "Life Cycle Perspective" mean in ISO 14001?', ['Only considering the production phase', 'Considering environmental aspects at all stages from raw material to disposal', 'Only the use phase', 'Only transportation'], 1, 'Life cycle perspective means considering environmental aspects at all stages: raw material acquisition, production, transportation, use, and end-of-life treatment.'),
  q('q5', 'Who must demonstrate leadership and commitment for the EMS?', ['Only the environmental manager', 'Top management', 'Only frontline workers', 'External consultants only'], 1, 'Top management must demonstrate leadership and commitment to the EMS, as required by Clause 5.'),
  q('q6', 'What is the "Prevention of Pollution" hierarchy?', ['Source reduction → Reuse → Recycle → Treatment → Disposal', 'Only end-of-pipe treatment', 'Only recycling', 'Only source reduction'], 0, 'The pollution prevention hierarchy is: Source reduction → Reuse → Recycle → Treatment → Disposal.'),
  q('q7', 'What are "Compliance Obligations"?', ['Only voluntary commitments', 'Legal requirements and other requirements the organization subscribes to', 'Only internal policies', 'Only customer requirements'], 1, 'Compliance obligations include legal requirements and other requirements the organization subscribes to related to its environmental aspects.'),
  q('q8', 'What is required for "Operational Control" in ISO 14001?', ['No controls needed', 'Controls for operations associated with significant environmental aspects', 'Only financial controls', 'Only HR controls'], 1, 'The organization must establish, implement, and maintain processes needed to meet operational planning and control requirements.'),
  q('q9', 'What is an "Environmental Objective"?', ['Only financial targets', 'Environmental goal consistent with the environmental policy', 'Only sales targets', 'Only production quotas'], 1, 'Environmental objectives are goals set by the organization consistent with its environmental policy, to be achieved.'),
  q('q10', 'What is the expected update year for ISO 14001 revision?', ['2024', '2025', '2026', '2028'], 2, 'ISO 14001 is currently under revision with an expected publication date in 2026.'),
  q('q11', 'What does "Emergency Preparedness and Response" require?', ['Only fire drills', 'Establishing processes to prepare for and respond to potential emergency situations', 'Only first aid training', 'Only evacuation plans'], 1, 'The organization must establish, implement, and maintain the processes needed to prepare for and respond to potential emergency situations.'),
  q('q12', 'What is "Monitoring and Measurement" in ISO 14001?', ['Only financial audits', 'Tracking environmental performance against criteria', 'Only employee surveys', 'Only customer feedback'], 1, 'The organization shall monitor, measure, analyze, and evaluate its environmental performance.'),
  q('q13', 'What is a "Significant Environmental Aspect"?', ['Any aspect that can be measured', 'An environmental aspect that has or can have a significant environmental impact', 'Only legal requirements', 'Only financial aspects'], 1, 'Significant environmental aspects are those that have or can have a significant environmental impact.'),
  q('q14', 'What is required for "Competence" (Clause 7.2)?', ['Only academic degrees', 'Determining necessary competence, ensuring training, and evaluating effectiveness', 'Only years of experience', 'Only certifications'], 1, 'The organization must determine the necessary competence, provide training, and evaluate the effectiveness of actions taken.'),
  q('q15', 'What is "External Communication" in ISO 14001?', ['Only marketing', 'Communication with external interested parties about environmental matters', 'Only internal memos', 'Only press releases'], 1, 'The organization must decide whether to communicate externally about its significant environmental aspects.'),
];

const iso45001Questions: QuizQuestion[] = [
  q('q1', 'What is ISO 45001:2018 replacing?', ['ISO 9001', 'OHSAS 18001', 'ISO 14001', 'ISO 27001'], 1, 'ISO 45001:2018 replaced OHSAS 18001 as the international standard for occupational health and safety management.'),
  q('q2', 'What is a "Hazard" in ISO 45001?', ['A financial risk', 'A source with potential to cause injury or ill health', 'A software bug', 'A marketing challenge'], 1, 'A hazard is a source with a potential to cause injury and ill health.'),
  q('q3', 'What is "Worker Participation"?', ['Only management decisions', 'Involvement of non-managerial workers in OH&S decision-making', 'Only union activities', 'Only safety training attendance'], 1, 'Worker participation is the involvement of non-managerial workers in OH&S decision-making processes.'),
  q('q4', 'What does the "Plan-Do-Check-Act" cycle apply to?', ['Only production processes', 'The entire OH&S management system', 'Only hiring processes', 'Only marketing'], 1, 'The PDCA methodology applies to the entire OH&S management system and its individual elements.'),
  q('q5', 'What is an "Incident" in ISO 45001?', ['Only major accidents', 'Occurrence arising from work that could or does result in injury or ill health', 'Only near misses', 'Only planned events'], 1, 'An incident is an occurrence arising out of, or in connection with work, that could or does result in injury and ill health.'),
  q('q6', 'What is "Risk Assessment"?', ['Only financial evaluation', 'Process of evaluating risks arising from hazards', 'Only equipment inspection', 'Only employee reviews'], 1, 'Risk assessment is the process of evaluating the risks arising from hazards, taking into account the adequacy of existing controls.'),
  q('q7', 'What is the hierarchy of controls?', ['PPE → Engineering → Administrative → Elimination', 'Elimination → Substitution → Engineering → Administrative → PPE', 'Training only', 'PPE only'], 1, 'The hierarchy of controls is: Elimination → Substitution → Engineering controls → Administrative controls → PPE.'),
  q('q8', 'What is a "Consultation" in ISO 45001?', ['Only management meetings', 'Seeking views before making decisions', 'Only union negotiations', 'Only customer feedback'], 1, 'Consultation is the seeking of views before making a decision, including worker participation.'),
  q('q9', 'What is required for "Legal and Other Requirements"?', ['Only voluntary standards', 'Identification of applicable legal requirements and compliance obligations', 'Only international standards', 'Only customer contracts'], 1, 'The organization must identify and have access to the legal requirements applicable to its OH&S hazards.'),
  q('q10', 'What is "Continual Improvement" in ISO 45001?', ['One-time changes', 'Ongoing process of enhancing OH&S performance', 'Annual audits only', 'Monthly inspections only'], 1, 'Continual improvement is the ongoing process of enhancing OH&S performance to achieve improvements in overall OH&S performance.'),
  q('q11', 'What does "Context of the Organization" include for OH&S?', ['Only financial context', 'Internal and external issues relevant to OH&S purpose and strategic direction', 'Only market trends', 'Only employee satisfaction'], 1, 'The organization must determine external and internal issues relevant to its purpose and strategic direction that affect its ability to achieve the intended outcomes.'),
  q('q12', 'What is a "Management of Change" process?', ['Only HR changes', 'Process to manage changes that could affect OH&S performance', 'Only IT updates', 'Only building renovations'], 1, 'The organization must establish processes for the implementation and control of planned changes that could affect OH&S performance.'),
  q('q13', 'What is "Performance Evaluation" in ISO 45001?', ['Only financial metrics', 'Monitoring, measurement, analysis, and evaluation of OH&S performance', 'Only production output', 'Only sales figures'], 1, 'Performance evaluation includes monitoring, measurement, analysis, and evaluation of OH&S performance.'),
  q('q14', 'What is "Root Cause Analysis"?', ['Blaming employees', 'A method to identify the underlying causes of incidents', 'Only immediate fixes', 'Financial analysis'], 1, 'Root cause analysis is a method used to identify the underlying causes of incidents or nonconformities.'),
  q('q15', 'What is an "OH&S Opportunity"?', ['Only financial gains', 'Circumstances that can lead to improvement of OH&S performance', 'Marketing opportunities', 'New hires only'], 1, 'OH&S opportunities are circumstances that can lead to the desirable consequence of improving OH&S performance.'),
];

const iso22000Questions: QuizQuestion[] = [
  q('q1', 'What is ISO 22000:2018?', ['A financial standard', 'A Food Safety Management System standard', 'An IT security standard', 'An environmental standard'], 1, 'ISO 22000:2018 specifies requirements for a food safety management system where an organization in the food chain needs to demonstrate its ability to control food safety hazards.'),
  q('q2', 'What are "Prerequisite Programs (PRPs)"?', ['Advanced software programs', 'Basic conditions and activities necessary to maintain a hygienic environment', 'Financial planning programs', 'Marketing programs'], 1, 'PRPs are the basic conditions and activities necessary to maintain a hygienic environment throughout the food chain.'),
  q('q3', 'What is HACCP?', ['A type of insurance', 'Hazard Analysis and Critical Control Points - a systematic preventive approach to food safety', 'A financial audit tool', 'A marketing framework'], 1, 'HACCP is a management system that addresses food safety through the analysis and control of biological, chemical, and physical hazards.'),
  q('q4', 'What is a "Critical Control Point (CCP)"?', ['Any point in the process', 'A step at which control can be applied to prevent or eliminate a food safety hazard', 'Only the final inspection point', 'Only the packaging stage'], 1, 'A CCP is a step at which control can be applied and is essential to prevent or eliminate a food safety hazard.'),
  q('q5', 'What is the "Food Safety Hazard"?', ['Only financial risks', 'A biological, chemical, or physical agent with potential to cause an adverse health effect', 'Only bacteria', 'Only chemicals'], 1, 'A food safety hazard is a biological, chemical, or physical agent in food with the potential to cause an adverse health effect.'),
  q('q6', 'What is "Traceability" in ISO 22000?', ['Only GPS tracking', 'The ability to follow the movement of food through specified stages', 'Only financial tracking', 'Only employee monitoring'], 1, 'Traceability is the ability to follow the movement of a food through specified stages of production, processing, and distribution.'),
  q('q7', 'What are "Operational PRPs"?', ['PRPs identified by the hazard analysis as essential to control food safety hazards', 'Only cleaning procedures', 'Only training programs', 'Only pest control'], 1, 'Operational PRPs are PRPs identified by the hazard analysis as essential in order to control the likelihood of introducing food safety hazards.'),
  q('q8', 'What is "Validation" in ISO 22000?', ['Only financial auditing', 'Obtaining evidence that control measures are capable of being effective', 'Only equipment testing', 'Only employee screening'], 1, 'Validation is obtaining evidence that the control measures managed by the HACCP plan and by the operational PRPs are capable of being effective.'),
  q('q9', 'What is "Withdrawal/Recall"?', ['Only employee dismissal', 'Removal of unsafe products from the market', 'Only equipment replacement', 'Only facility closure'], 1, 'The organization must establish systems to enable the complete, timely withdrawal of lots of end products that have been identified as unsafe.'),
  q('q10', 'What is the role of "Top Management" in ISO 22000?', ['Only financial oversight', 'Demonstrating leadership and commitment to the FSMS', 'Only marketing decisions', 'Only hiring staff'], 1, 'Top management must demonstrate leadership and commitment to the FSMS, including establishing the food safety policy.'),
  q('q11', 'What is a "Food Safety Team"?', ['A marketing team', 'A group responsible for developing, implementing, and maintaining the FSMS', 'A cleaning crew', 'A sales team'], 1, 'The food safety team is responsible for developing, implementing, and maintaining the FSMS, including the HACCP plan.'),
  q('q12', 'What is "Monitoring" in HACCP?', ['Only financial tracking', 'Conducting a planned sequence of observations or measurements', 'Only employee attendance', 'Only customer feedback'], 1, 'Monitoring is conducting a planned sequence of observations or measurements to assess whether control measures are operating as intended.'),
  q('q13', 'What is "Corrective Action" in ISO 22000?', ['Only immediate fixes', 'Action to identify and eliminate the cause of a detected nonconformity', 'Blaming employees', 'Ignoring the problem'], 1, 'Corrective action is any action to eliminate the cause of a detected nonconformity or other undesirable situation.'),
  q('q14', 'What does "Interactive Communication" mean?', ['Only internal memos', 'Communication throughout the food chain about food safety hazards', 'Only press releases', 'Only social media'], 1, 'Interactive communication ensures that sufficient information on hazards is available at all steps of the food chain.'),
  q('q15', 'What is "Updating" in ISO 22000?', ['Only software updates', 'Regular evaluation and updating of preliminary information and data', 'Only equipment replacement', 'Only hiring new staff'], 1, 'The organization must ensure that the preliminary information and data specified are kept up to date.'),
];

const iso27001Questions: QuizQuestion[] = [
  q('q1', 'What is ISO 27001:2022?', ['A quality management standard', 'An Information Security Management System standard', 'An environmental standard', 'A financial standard'], 1, 'ISO/IEC 27001:2022 specifies the requirements for establishing, implementing, maintaining, and continually improving an ISMS.'),
  q('q2', 'What are the three pillars of Information Security?', ['Hardware, Software, Network', 'Confidentiality, Integrity, Availability (CIA)', 'People, Process, Technology', 'Prevention, Detection, Response'], 1, 'The three fundamental pillars are Confidentiality (ensuring authorized access), Integrity (safeguarding accuracy), and Availability (ensuring timely access).'),
  q('q3', 'What is an "Information Security Risk Assessment"?', ['Only financial evaluation', 'Identifying risks and evaluating their significance', 'Only hardware inspection', 'Only employee reviews'], 1, 'Risk assessment includes risk identification, risk analysis, and risk evaluation.'),
  q('q4', 'What is a "Statement of Applicability" (SoA)?', ['A financial statement', 'A document identifying controls selected and their justification', 'A marketing document', 'An employee handbook'], 1, 'The SoA is a document that identifies the controls selected for the organization and their justification for inclusion or exclusion.'),
  q('q5', 'What is the "Annex A" in ISO 27001:2022?', ['A financial appendix', 'A set of 93 information security controls organized into 4 themes', 'A list of employees', 'A marketing plan'], 1, 'Annex A contains 93 security controls organized into 4 themes: Organizational, People, Physical, and Technological.'),
  q('q6', 'What is a "Security Incident"?', ['Only physical theft', 'A single or series of unwanted security events with significant probability of compromising business operations', 'Only cyber attacks', 'Only employee mistakes'], 1, 'A security incident is a single or a series of unwanted or unexpected information security events that have a significant probability of compromising business operations.'),
  q('q7', 'What is "Access Control"?', ['Only password policies', 'Restricting access to information and information processing facilities', 'Only physical locks', 'Only firewalls'], 1, 'Access control means restricting access to information and information processing facilities to authorized persons.'),
  q('q8', 'What is the purpose of "Cryptographic Controls"?', ['Only password hashing', 'Protecting the confidentiality, authenticity, and integrity of information', 'Only file compression', 'Only data backup'], 1, 'Cryptographic controls protect the confidentiality, authenticity, and integrity of information by transforming data into an unreadable format.'),
  q('q9', 'What is "Business Continuity" in ISO 27001?', ['Only financial planning', 'Protecting critical business processes from major failures', 'Only marketing campaigns', 'Only HR policies'], 1, 'Information security aspects of business continuity protect critical business processes from the effects of major failures or disasters.'),
  q('q10', 'What is a "Security Policy"?', ['A marketing document', 'Management direction and support for information security', 'An employee contract', 'A sales strategy'], 1, 'The information security policy is management direction and support for information security in accordance with business requirements.'),
  q('q11', 'What are "Security Roles and Responsibilities"?', ['Only IT department duties', 'Defined and allocated security roles and responsibilities', 'Only management duties', 'Only external consultant duties'], 1, 'All information security responsibilities must be defined and allocated.'),
  q('q12', 'What is "Risk Treatment" in ISO 27001?', ['Ignoring risks', 'Selecting appropriate risk treatment options and controls', 'Only risk avoidance', 'Only risk transfer'], 1, 'Risk treatment involves selecting appropriate risk treatment options and necessary controls to implement those options.'),
  q('q13', 'What is the purpose of "Internal Audit" in ISO 27001?', ['Punishing employees', 'Determining whether the ISMS conforms to requirements', 'Replacing management review', 'Eliminating external audits'], 1, 'Internal audits determine whether the ISMS conforms to the organization\'s own requirements and ISO 27001 requirements.'),
  q('q14', 'What is "Supplier Relationships" security about?', ['Only financial agreements', 'Agreements with suppliers to address information security risks', 'Only hiring processes', 'Only marketing partnerships'], 1, 'The organization must agree and document relevant information security requirements with suppliers.'),
  q('q15', 'What is "Continuous Improvement" in ISO 27001?', ['One-time changes', 'The ongoing effort to improve the suitability, adequacy, and effectiveness of the ISMS', 'Annual audits only', 'Monthly reports only'], 1, 'The organization must continually improve the suitability, adequacy, and effectiveness of the ISMS.'),
];

const imsQuestions: QuizQuestion[] = [
  q('q1', 'What is an Integrated Management System (IMS)?', ['A software application', 'A combined management system for multiple ISO standards', 'A financial system', 'A marketing strategy'], 1, 'An IMS combines multiple management systems (e.g., ISO 9001, ISO 14001, ISO 45001) into one unified system with shared processes.'),
  q('q2', 'Which standards are commonly integrated in an IMS?', ['Only ISO 9001', 'ISO 9001, ISO 14001, ISO 45001', 'Only ISO 27001', 'Only ISO 22000'], 1, 'The most common integration is ISO 9001 (Quality), ISO 14001 (Environment), and ISO 45001 (OH&S).'),
  q('q3', 'What is the benefit of an IMS?', ['Only cost reduction', 'Reduced duplication, improved efficiency, and streamlined processes', 'Only employee satisfaction', 'Only marketing value'], 1, 'An IMS reduces duplication, improves efficiency, and streamlines processes across multiple standards.'),
  q('q4', 'What is the Annex SL High Level Structure?', ['A software framework', 'A common structure shared by multiple ISO management system standards', 'A financial reporting standard', 'A marketing framework'], 1, 'Annex SL provides the common top-level structure used by multiple ISO management system standards.'),
  q('q5', 'How are audits conducted in an IMS?', ['Separate audits for each standard', 'Combined audits covering all integrated standards', 'Only annual audits', 'Only external audits'], 1, 'IMS audits can be conducted as combined audits covering all integrated standards simultaneously.'),
  q('q6', 'What is the role of a "Management Representative" in IMS?', ['Only financial reporting', 'Coordinating the IMS across all integrated standards', 'Only HR duties', 'Only marketing'], 1, 'The management representative coordinates the IMS activities across all integrated standards.'),
  q('q7', 'What are common processes that can be shared in an IMS?', ['Only financial processes', 'Document control, internal audits, management review, corrective actions', 'Only production processes', 'Only sales processes'], 1, 'Common shared processes include document control, internal audits, management review, and corrective actions.'),
  q('q8', 'What is the purpose of an IMS Policy?', ['Only marketing', 'A unified policy addressing all integrated standards', 'Only employee relations', 'Only customer communication'], 1, 'An IMS policy is a unified policy that addresses the requirements of all integrated management system standards.'),
  q('q9', 'What is "Risk-Based Thinking" in IMS context?', ['Only financial risks', 'Considering risks and opportunities across all standards', 'Only environmental risks', 'Only safety risks'], 1, 'Risk-based thinking in IMS considers risks and opportunities across all integrated standards holistically.'),
  q('q10', 'What is the most common challenge in IMS implementation?', ['Lack of standards', 'Ensuring all requirements of each standard are fully addressed without conflict', 'Too many employees', 'Too many customers'], 1, 'The most common challenge is ensuring all requirements of each standard are fully addressed without conflict.'),
  q('q11', 'What is "Combined Audit"?', ['Only financial audit', 'An audit that assesses compliance with multiple standards simultaneously', 'Only external audit', 'Only internal audit'], 1, 'A combined audit assesses compliance with multiple management system standards simultaneously.'),
  q('q12', 'What does "Integration" mean in IMS?', ['Only software integration', 'The seamless combination of multiple management systems into one', 'Only financial integration', 'Only HR integration'], 1, 'Integration in IMS means the seamless combination of multiple management systems into one cohesive system.'),
  q('q13', 'What is the role of "Top Management" in IMS?', ['Only financial oversight', 'Demonstrating leadership and commitment across all integrated standards', 'Only hiring', 'Only marketing decisions'], 1, 'Top management must demonstrate leadership and commitment to all integrated management system standards.'),
  q('q14', 'What are "Objectives" in IMS?', ['Only financial targets', 'Measurable objectives consistent with the integrated policy across all standards', 'Only production quotas', 'Only sales targets'], 1, 'IMS objectives are measurable objectives consistent with the integrated policy across all standards.'),
  q('q15', 'What is the Exemplar Global competency unit for IMS?', ['TL 9001 only', 'TL Management Systems Lead Auditors (covering multiple standards)', 'Only EM Environmental', 'Only OH 45001'], 1, 'The Exemplar Global competency unit is TL Management Systems Lead Auditors, which covers multiple standards.'),
];

const esgQuestions: QuizQuestion[] = [
  q('q1', 'What does ESG stand for?', ['Economic, Social, and Governance', 'Environmental, Social, and Governance', 'Environmental, Strategic, and Growth', 'Economic, Strategic, and Governance'], 1, 'ESG stands for Environmental, Social, and Governance - the three central factors in measuring the sustainability and societal impact of an investment.'),
  q('q2', 'What is a "Materiality Assessment"?', ['A financial audit', 'A process to identify and prioritize ESG issues important to stakeholders', 'A building inspection', 'An employee satisfaction survey only'], 1, 'A materiality assessment is a process to identify, refine, and assess ESG topics that are most important to stakeholders and the business.'),
  q('q3', 'Which organization developed the GRI Standards?', ['United Nations', 'Global Reporting Initiative', 'OECD', 'World Bank'], 1, 'The Global Reporting Initiative (GRI) developed the GRI Standards, the most widely used standards for sustainability reporting worldwide.'),
  q('q4', 'What does TCFD stand for?', ['Task Force on Climate-related Financial Disclosures', 'Total Carbon Footprint Declaration', 'Technical Committee on Financial Development', 'Trade Center for Financial Development'], 0, 'TCFD stands for Task Force on Climate-related Financial Disclosures.'),
  q('q5', 'What is "Greenwashing"?', ['Using green paint on products', 'Making misleading claims about environmental benefits', 'Washing products with recycled water', 'A type of environmental cleaning service'], 1, 'Greenwashing is the practice of making misleading or unsubstantiated claims about the environmental benefits of a product, service, or company practice.'),
  q('q6', 'What is the primary goal of ESG reporting?', ['To replace financial reporting', 'To provide transparent, comparable ESG performance data to stakeholders', 'To avoid taxes', 'To reduce employee salaries'], 1, 'ESG reporting aims to provide transparent, comparable, and decision-useful data on ESG performance to stakeholders.'),
  q('q7', 'Which of the following is a Social (S) factor in ESG?', ['Board diversity', 'Labor practices and human rights', 'Anti-corruption policies', 'Shareholder rights'], 1, 'Labor practices and human rights are key Social factors in ESG.'),
  q('q8', 'What is the purpose of SASB?', ['To audit financial statements', 'To provide industry-specific standards for disclosing sustainability information to investors', 'To regulate stock markets', 'To manage employee payroll'], 1, 'SASB provides industry-specific standards for disclosing financially material sustainability information to investors.'),
  q('q9', 'Which UN body adopted the 17 SDGs?', ['UNESCO', 'UN General Assembly', 'WHO', 'IMF'], 1, 'The 17 Sustainable Development Goals were adopted by all United Nations Member States in 2015.'),
  q('q10', 'What is "Stakeholder Engagement" in ESG?', ['Only shareholder meetings', 'The process of identifying and engaging with parties affected by or affecting the organization', 'Only employee surveys', 'Only customer feedback'], 1, 'Stakeholder engagement is the process of identifying and engaging with parties affected by or affecting the organization\'s ESG activities.'),
];

const governanceQuestions: QuizQuestion[] = [
  q('q1', 'What is the primary purpose of Corporate Governance?', ['To maximize shareholder wealth at any cost', 'To provide the structure through which company objectives are set and monitored', 'To eliminate the board of directors', 'To reduce employee benefits'], 1, 'Corporate governance is the system by which companies are directed and controlled.'),
  q('q2', 'What is the role of the Board of Directors?', ['Only attend meetings', 'Strategic guidance, oversight of management, and accountability', 'Manage day-to-day operations', 'Hire and fire only junior employees'], 1, 'The Board provides strategic guidance, effective oversight of management, and is accountable to shareholders.'),
  q('q3', 'What does "Board Independence" mean?', ['The board meets in a different country', 'Directors who have no material relationship with the company', 'The board makes all decisions alone', 'The board has no meetings'], 1, 'Independent directors have no material relationship with the company other than their board seat.'),
  q('q4', 'What is the purpose of the Audit Committee?', ['To plan company parties', 'To oversee financial reporting, internal controls, and the audit process', 'To manage marketing campaigns', 'To hire cleaning staff'], 1, 'The Audit Committee oversees the integrity of financial statements, compliance, and external auditors.'),
  q('q5', 'What is "Whistleblowing"?', ['Blowing a physical whistle', 'Disclosure of illegal, immoral, or illegitimate practices', 'A type of insurance', 'A marketing technique'], 1, 'Whistleblowing is the disclosure by organization members of illegal, immoral, or illegitimate practices under the control of their employers.'),
  q('q6', 'What is a "Conflict of Interest"?', ['A disagreement between employees', 'A situation where personal interests could interfere with professional duties', 'A competition between companies', 'A labor strike'], 1, 'A conflict of interest occurs when an individual\'s personal interests could potentially interfere with their professional duties.'),
  q('q7', 'What is "Related Party Transactions"?', ['Transactions with customers', 'Transactions between the company and its directors, officers, or significant shareholders', 'Transactions with suppliers', 'Transactions with government'], 1, 'Related party transactions are transfers between the company and its related parties (directors, officers, significant shareholders).'),
  q('q8', 'What is the OECD Corporate Governance Principles?', ['Only financial regulations', 'An international benchmark for corporate governance', 'Only labor laws', 'Only tax guidelines'], 1, 'The OECD Principles provide an international benchmark for policymakers, regulators, and market participants.'),
  q('q9', 'What is "Executive Compensation" governance about?', ['Only base salary', 'Aligning executive interests with long-term shareholder value', 'Reducing all executive pay', 'Eliminating bonuses'], 1, 'Executive compensation governance focuses on aligning executive interests with long-term shareholder value creation.'),
  q('q10', 'What is the purpose of a Compliance Management System?', ['To ignore regulations', 'To ensure the organization adheres to laws, regulations, and policies', 'To reduce employee count', 'To avoid paying taxes'], 1, 'A CMS ensures the organization adheres to relevant laws, regulations, standards, and internal policies.'),
];

const riskQuestions: QuizQuestion[] = [
  q('q1', 'What is ISO 31000 primarily concerned with?', ['Financial accounting', 'Risk management - principles and guidelines', 'Human resources management', 'Marketing strategies'], 1, 'ISO 31000 provides principles, a framework, and a process for managing risk.'),
  q('q2', 'How many principles of risk management are in ISO 31000?', ['5', '8', '10', '7'], 1, 'ISO 31000 defines 8 principles of risk management.'),
  q('q3', 'What is "Risk Appetite"?', ['Amount of risk an organization is willing to pursue or retain', 'Physical hunger of employees', 'Financial budget for insurance', 'Number of risk managers hired'], 0, 'Risk appetite is the amount and type of risk that an organization is willing to pursue or retain.'),
  q('q4', 'What is a "Risk Register"?', ['A financial ledger', 'A document recording identified risks, analysis, and treatment plans', 'An employee attendance sheet', 'A marketing contact list'], 1, 'A Risk Register records identified risks, their analysis and evaluation, and planned treatment measures.'),
  q('q5', 'What does "Residual Risk" mean?', ['Risk before treatment', 'Risk remaining after risk treatment has been applied', 'Risk that has been eliminated', 'Risk transferred to another company'], 1, 'Residual risk is the risk remaining after risk treatment has been applied.'),
  q('q6', 'What is the difference between a "Threat" and an "Opportunity"?', ['No difference', 'A threat is a potential negative impact; an opportunity is a potential positive impact', 'Both are only financial', 'Both are only external'], 1, 'In ISO 31000, risk can have both negative effects (threats) and positive effects (opportunities).'),
  q('q7', 'What does "Risk Treatment" involve?', ['Only avoiding risk', 'Selecting and implementing measures to modify risk', 'Ignoring all risks', 'Only buying insurance'], 1, 'Risk treatment involves selecting and implementing options for modifying risk: avoiding, taking, removing, changing, sharing, or retaining risk.'),
  q('q8', 'What is a "Risk Heat Map"?', ['A weather map', 'A visual representation of risks plotted based on likelihood and impact', 'A temperature control system', 'A fire safety plan'], 1, 'A Risk Heat Map plots risks on a grid based on their likelihood (probability) and impact (consequence).'),
  q('q9', 'What technique is commonly used for risk identification?', ['Brainstorming', 'Social media posting', 'Employee salary negotiation', 'Office decoration planning'], 0, 'Brainstorming is one of the most commonly used techniques for risk identification.'),
  q('q10', 'What is the ISO 31000 risk management process?', ['Plan-Do-Check-Act', 'Communication, Context, Risk Assessment, Treatment, Monitoring', 'Hire-Fire-Train', 'Budget-Spend-Audit'], 1, 'The ISO 31000 process includes: Communication, Context, Risk Assessment, Risk Treatment, and Monitoring & Review.'),
];

export const courseExams: CourseExam[] = [
  { courseId: 'iso-9001-la', title: 'ISO 9001:2015 Lead Auditor Final Assessment', description: 'Comprehensive 15-question assessment covering all aspects of ISO 9001:2015 Lead Auditor training. You need 80% to pass and receive your Lead Auditor certificate.', passingScore: 80, questions: iso9001Questions },
  { courseId: 'iso-14001-la', title: 'ISO 14001:2015 Lead Auditor Final Assessment', description: 'Comprehensive assessment covering environmental management systems, life cycle perspective, and the upcoming 2026 revision. You need 80% to pass.', passingScore: 80, questions: iso14001Questions },
  { courseId: 'iso-45001-la', title: 'ISO 45001:2018 Lead Auditor Final Assessment', description: 'Assessment covering occupational health and safety management, hazard identification, risk assessment, and the hierarchy of controls. You need 80% to pass.', passingScore: 80, questions: iso45001Questions },
  { courseId: 'iso-22000-la', title: 'ISO 22000:2018 Lead Auditor Final Assessment', description: 'Assessment covering food safety management, HACCP principles, prerequisite programs, and FSMS implementation. You need 80% to pass.', passingScore: 80, questions: iso22000Questions },
  { courseId: 'iso-27001-la', title: 'ISO 27001:2022 Lead Auditor Final Assessment', description: 'Assessment covering information security management, Annex A controls, risk treatment, and the CIA triad. You need 80% to pass.', passingScore: 80, questions: iso27001Questions },
  { courseId: 'ims-la', title: 'Integrated Management Systems (IMS) Lead Auditor Assessment', description: 'Assessment covering the integration of ISO 9001, ISO 14001, and ISO 45001 management systems. You need 80% to pass.', passingScore: 80, questions: imsQuestions },
  { courseId: 'esg-strategy', title: 'ESG Strategy & Reporting Assessment', description: 'Test your understanding of ESG frameworks, materiality assessment, and sustainability reporting. You need 75% to pass.', passingScore: 75, questions: esgQuestions },
  { courseId: 'governance', title: 'Corporate Governance Final Assessment', description: 'Comprehensive assessment covering governance frameworks, board effectiveness, and compliance management. You need 80% to pass.', passingScore: 80, questions: governanceQuestions },
  { courseId: 'risk-31000', title: 'ISO 31000 Risk Management Assessment', description: 'Test your knowledge of enterprise risk management principles and techniques. You need 75% to pass.', passingScore: 75, questions: riskQuestions },
];

export function getExamForCourse(courseId: string): CourseExam | undefined {
  return courseExams.find(e => e.courseId === courseId);
}

export function calculateScore(answers: Record<string, number>, questions: QuizQuestion[]): number {
  let correct = 0;
  questions.forEach(q => {
    if (answers[q.id] === q.correctIndex) correct++;
  });
  return Math.round((correct / questions.length) * 100);
}
