export interface IssuedCertificate {
  certificateId: string;
  holderName: string;
  standard: string;
  standardShort: string;
  title: string;
  issueDate: string;
  expiryDate: string;
  status: 'ACTIVE' | 'EXPIRED' | 'REVOKED';
  hours: number;
  location: string;
  image: string;
  trainer: string;
  certifyingBody: string;
}

// All 13 issued certificates from Pioneers International
export const issuedCertificates: IssuedCertificate[] = [
  {
    certificateId: 'ISOTQM002',
    holderName: 'Wael Saleh Alkhatib',
    standard: 'ISO 9001:2015',
    standardShort: 'ISO 9001',
    title: 'Lead Auditor Training Course - Quality Management System',
    issueDate: 'June 18, 2025',
    expiryDate: 'June 18, 2035',
    status: 'ACTIVE',
    hours: 40,
    location: 'Amman, Jordan',
    image: '/assets/certificates/WAEL-9001.jpg',
    trainer: 'Wael S. Alkhatib',
    certifyingBody: 'Exemplar Global',
  },
  {
    certificateId: 'ISOEMS002',
    holderName: 'Wael Saleh Alkhatib',
    standard: 'ISO 14001:2015',
    standardShort: 'ISO 14001',
    title: 'Lead Auditor Training Course - Environmental Management System',
    issueDate: 'June 22, 2025',
    expiryDate: 'June 22, 2035',
    status: 'ACTIVE',
    hours: 40,
    location: 'Amman, Jordan',
    image: '/assets/certificates/WAEL-14001.jpg',
    trainer: 'Wael S. Alkhatib',
    certifyingBody: 'Exemplar Global',
  },
  {
    certificateId: 'ISOOHSM002',
    holderName: 'Wael Saleh Alkhatib',
    standard: 'ISO 45001:2018',
    standardShort: 'ISO 45001',
    title: 'Lead Auditor Training Course - Occupational Health & Safety Management System',
    issueDate: 'June 29, 2025',
    expiryDate: 'June 29, 2035',
    status: 'ACTIVE',
    hours: 40,
    location: 'Amman, Jordan',
    image: '/assets/certificates/WAEL-45001.jpg',
    trainer: 'Wael S. Alkhatib',
    certifyingBody: 'Exemplar Global',
  },
  {
    certificateId: 'ISOFSM001',
    holderName: 'Eng. Ghaith Jamal Alkhatib',
    standard: 'ISO 22000:2018',
    standardShort: 'ISO 22000',
    title: 'Lead Auditor Training Course - Food Safety Management System',
    issueDate: 'June 18, 2025',
    expiryDate: 'June 18, 2035',
    status: 'ACTIVE',
    hours: 40,
    location: 'Amman, Jordan',
    image: '/assets/certificates/GHAITH22000.jpg',
    trainer: 'Wael S. Alkhatib',
    certifyingBody: 'Exemplar Global',
  },
  {
    certificateId: 'ISOTQM009',
    holderName: 'Islam Attallah Nasir Alrawahneh',
    standard: 'ISO 9001:2015',
    standardShort: 'ISO 9001',
    title: 'Lead Auditor Training Course - Quality Management System',
    issueDate: 'January 19, 2026',
    expiryDate: 'January 19, 2036',
    status: 'ACTIVE',
    hours: 40,
    location: 'Amman, Jordan',
    image: '/assets/certificates/ISLAM-9001.jpg',
    trainer: 'Wael S. Alkhatib',
    certifyingBody: 'Exemplar Global',
  },
  {
    certificateId: 'IMS-LA-003',
    holderName: 'Majdi Saleh Ahmad Alhnaity',
    standard: 'ISO 9001:2015 / ISO 14001:2015 / ISO 45001:2018',
    standardShort: 'IMS',
    title: 'Lead Auditor in Integrated Management Systems (IMS)',
    issueDate: 'January 19, 2026',
    expiryDate: 'January 19, 2036',
    status: 'ACTIVE',
    hours: 40,
    location: 'Amman, Jordan',
    image: '/assets/certificates/MAJDI-IMS.jpg',
    trainer: 'Wael S. Alkhatib',
    certifyingBody: 'Exemplar Global',
  },
  {
    certificateId: 'ISOEMS003',
    holderName: 'Mohammed',
    standard: 'ISO 14001:2015',
    standardShort: 'ISO 14001',
    title: 'Lead Auditor Training Course - Environmental Management System',
    issueDate: '2025',
    expiryDate: '2035',
    status: 'ACTIVE',
    hours: 40,
    location: 'Amman, Jordan',
    image: '/assets/certificates/Mohammed-14001.jpg',
    trainer: 'Wael S. Alkhatib',
    certifyingBody: 'Exemplar Global',
  },
  {
    certificateId: 'ISOISMS001',
    holderName: 'Mohammed',
    standard: 'ISO 27001:2022',
    standardShort: 'ISO 27001',
    title: 'Lead Auditor Training Course - Information Security Management System',
    issueDate: '2025',
    expiryDate: '2035',
    status: 'ACTIVE',
    hours: 40,
    location: 'Amman, Jordan',
    image: '/assets/certificates/Mohammed-27001.jpg',
    trainer: 'Wael S. Alkhatib',
    certifyingBody: 'Exemplar Global',
  },
  {
    certificateId: 'ISOISMS002',
    holderName: 'Mohammed',
    standard: 'ISO 27001:2022',
    standardShort: 'ISO 27001',
    title: 'Lead Auditor Training Course - Information Security Management System',
    issueDate: '2025',
    expiryDate: '2035',
    status: 'ACTIVE',
    hours: 40,
    location: 'Amman, Jordan',
    image: '/assets/certificates/Mohammed-27001-2.jpg',
    trainer: 'Wael S. Alkhatib',
    certifyingBody: 'Exemplar Global',
  },
  {
    certificateId: 'ISOOHSM003',
    holderName: 'Mohammed',
    standard: 'ISO 45001:2018',
    standardShort: 'ISO 45001',
    title: 'Lead Auditor Training Course - Occupational Health & Safety Management System',
    issueDate: '2025',
    expiryDate: '2035',
    status: 'ACTIVE',
    hours: 40,
    location: 'Amman, Jordan',
    image: '/assets/certificates/Mohammed-45001.jpg',
    trainer: 'Wael S. Alkhatib',
    certifyingBody: 'Exemplar Global',
  },
  {
    certificateId: 'ISOTQM010',
    holderName: 'Qusai Hindi',
    standard: 'ISO 9001:2015',
    standardShort: 'ISO 9001',
    title: 'Lead Auditor Training Course - Quality Management System',
    issueDate: '2025',
    expiryDate: '2035',
    status: 'ACTIVE',
    hours: 40,
    location: 'Amman, Jordan',
    image: '/assets/certificates/Qusai-Hindi.jpg',
    trainer: 'Wael S. Alkhatib',
    certifyingBody: 'Exemplar Global',
  },
  {
    certificateId: 'ISOTQM011',
    holderName: 'Tala',
    standard: 'ISO 9001:2015',
    standardShort: 'ISO 9001',
    title: 'Lead Auditor Training Course - Quality Management System',
    issueDate: '2025',
    expiryDate: '2035',
    status: 'ACTIVE',
    hours: 40,
    location: 'Amman, Jordan',
    image: '/assets/certificates/TALA-9001.jpg',
    trainer: 'Wael S. Alkhatib',
    certifyingBody: 'Exemplar Global',
  },
  {
    certificateId: 'ISOISMS003',
    holderName: 'Tala',
    standard: 'ISO 27001:2022',
    standardShort: 'ISO 27001',
    title: 'Lead Auditor Training Course - Information Security Management System',
    issueDate: '2025',
    expiryDate: '2035',
    status: 'ACTIVE',
    hours: 40,
    location: 'Amman, Jordan',
    image: '/assets/certificates/TALA-27001.jpg',
    trainer: 'Wael S. Alkhatib',
    certifyingBody: 'Exemplar Global',
  },
];

export function findCertificateById(id: string): IssuedCertificate | undefined {
  return issuedCertificates.find(c =>
    c.certificateId.toLowerCase() === id.toLowerCase() ||
    c.certificateId.toLowerCase().replace('#', '') === id.toLowerCase().replace('#', '')
  );
}

export function getAllCertificateIds(): string[] {
  return issuedCertificates.map(c => c.certificateId);
}
